all:
  children:
    repo-servers:
      hosts:
        repo-server:
          ansible_host: 194.9.80.38
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
